# Generated by Django 3.2.25 on 2026-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='activity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='diet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
