# Generated by Django 3.2.25 on 2026-05-31 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellness_app', '0002_auto_20260523_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='activity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('workout', models.CharField(blank=True, choices=[('running', '🏃 Running'), ('cycling', '🚴 Cycling'), ('weights', '🏋️ Weights'), ('swimming', '🏊 Swimming'), ('yoga', '🧘 Yoga'), ('hiit', '⚡ HIIT'), ('walking', '🚶 Walking'), ('rest', '😴 Rest Day'), ('other', '🎯 Other')], max_length=50)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('intensity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('mood', models.IntegerField(blank=True, choices=[(1, '😞 Terrible'), (2, '😕 Bad'), (3, '😐 Okay'), (4, '😊 Good'), (5, '🔥 Amazing')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
