# Generated by Django 3.2.25 on 2026-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0003_auto_20260531_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesslog',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
